=== DamianHr/RPG_Maker_Esgi/application/schemas/gameFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="game" type="gameFileType">

        <!-- Makes ids unique within their scope -->

        <xs:unique name="situationKey">
            <xs:selector xpath="./situation"/>
            <xs:field xpath="@code"/>
        </xs:unique>

        <xs:unique name="answerKey">
            <xs:selector xpath="./situation/question/answerpool/answer"/>
            <xs:field xpath="@code"/>
        </xs:unique>

        <!--Force goTo to actually ref a situation-->
        <xs:keyref name="childKeyRefId" refer="refedId">
            <xs:selector xpath="./situation/question/answerpool/answer"/>
            <xs:field xpath="@goTo"/>
        </xs:keyref>
        <xs:key name="situationId">
            <xs:selector xpath="./situation"/>
            <xs:field xpath="@code"/>
        </xs:key>
    </xs:element>

    <xs:complexType name="gameFileType">
        <xs:sequence>
            <xs:element type="situationType" name="situation" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="titre" use="required"/>
    </xs:complexType>



    <xs:complexType name="situationType">
        <xs:sequence>
            <xs:element type="xs:string" name="exposition">
            </xs:element>
            <xs:element type="questionType" name="question" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:integer" name="code" use="required"/>
    </xs:complexType>

    <xs:complexType name="answerpoolType">
        <xs:sequence>
            <!--If only one answer is available there's no use to prompt the user...-->
            <xs:element type="answerType" name="answer" maxOccurs="unbounded" minOccurs="2"/>
                <!--TODO make answer@code unique within answerpools + use key/keyref to check if it goes somewhere !-->

        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="authorType">
        <xs:sequence>
            <xs:element type="xs:string" name="nickname"/>
        </xs:sequence>
        <xs:attribute type="xs:long" name="id" use="required"/>
    </xs:complexType>


    <xs:complexType name="answerType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="code" use="required"/>
                <xs:attribute type="xs:string" name="value" use="required"/>
                <xs:attribute type="xs:string" name="goTo" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="questionType">
        <xs:sequence>
            <xs:element type="answerpoolType" name="answerpool">
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="label" use="required"/>
    </xs:complexType>
</xs:schema>

=== DamianHr/RPG_Maker_Esgi/application/database/games/otherGame.xml
<?xml version="1.0"?>
<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../schemas/gameFile.xsd">

    <title>other Game</title>
    <situation code="0">
        <exposition>You're in some place somewhere</exposition>
        <question label="You don't look around, cause you're blind as fuck.">
            <answerpool>
                <answer code="0" value="0" goTo="0">You decide to stay here</answer>
                <answer code="1" value="-1" goTo="1">You take one step ahead</answer>
            </answerpool>
        </question>
    </situation>
    <situation code="1">
        <exposition>You bat-eyed basterd has make a bad decision, you happened to be on the edge of a cliff. Poor thing,
            you're dead
        </exposition>
    </situation>
    <situation code="2">
        <exposition>You're in some place somewhere</exposition>
        <question label="You don't look around, cause you're blind as fuck.">
            <answerpool>
                <answer code="3" value="0" goTo="0">You decide to stay here</answer>
                <answer code="4" value="-1" goTo="1">You take one step ahead</answer>
            </answerpool>
        </question>
    </situation>
</game>
